version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: log_db
    restart: always
    environment:
      POSTGRES_USER: log_user
      POSTGRES_PASSWORD: log_pass
      POSTGRES_DB: log_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  bot:
    build: .
    container_name: log_bot
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - ./media:/app/media

volumes:
  postgres_data:
